import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Data Systems — Black Panther Portfolio",
  description: "Dark-themed data scientist portfolio generated by Figma Make.",
};

// Browser extensions (Bitdefender, Grammarly, ColorZilla, LanguageTool, ...) inject
// attributes such as `bis_skin_checked` into the DOM before React hydrates. React treats
// those extra attributes as hydration mismatches and `suppressHydrationWarning` on a
// single element only covers that element, not its children. Strip the known attributes
// before hydration and keep observing briefly in case an extension injects them late.
const extensionAttributeGuard = `(function () {
  var ATTRS = [
    "bis_skin_checked",
    "bis_register",
    "cz-shortcut-listen",
    "data-gr-ext-installed",
    "data-new-gr-c-s-check-loaded",
    "data-lt-installed",
    "data-lt-tmp-id",
    "data-lastpass-icon-root",
    "data-lastpass-root",
    "fdprocessedid",
    "data-google-query-id"
  ];
  var PREFIXES = ["__processed_"];
  function isExtensionAttribute(name) {
    if (!name) return false;
    if (ATTRS.indexOf(name) !== -1) return true;
    for (var i = 0; i < PREFIXES.length; i++) {
      if (name.indexOf(PREFIXES[i]) === 0) return true;
    }
    return false;
  }
  function stripElement(element) {
    if (!element || element.nodeType !== 1) return;
    var attributes = element.attributes;
    for (var i = attributes.length - 1; i >= 0; i--) {
      if (isExtensionAttribute(attributes[i].name)) {
        element.removeAttribute(attributes[i].name);
      }
    }
  }
  function stripTree(root) {
    if (!root || root.nodeType !== 1) return;
    stripElement(root);
    var elements = root.querySelectorAll("*");
    for (var i = 0; i < elements.length; i++) stripElement(elements[i]);
  }
  stripTree(document.documentElement);
  if (typeof MutationObserver === "undefined") return;
  var observer = new MutationObserver(function (mutations) {
    for (var i = 0; i < mutations.length; i++) {
      var mutation = mutations[i];
      if (mutation.type === "attributes") {
        if (isExtensionAttribute(mutation.attributeName)) {
          mutation.target.removeAttribute(mutation.attributeName);
        }
      } else {
        for (var j = 0; j < mutation.addedNodes.length; j++) {
          stripTree(mutation.addedNodes[j]);
        }
      }
    }
  });
  observer.observe(document.documentElement, {
    attributes: true,
    childList: true,
    subtree: true
  });
  window.setTimeout(function () {
    observer.disconnect();
  }, 15000);
})();`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: extensionAttributeGuard }} />
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
